# Generated by Django 5.0.1 on 2024-01-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_description', models.CharField(max_length=500, verbose_name='Главное описание')),
                ('title_1', models.CharField(max_length=255, verbose_name='Название 1')),
                ('description_1', models.CharField(max_length=255, verbose_name='Описание 1')),
                ('title_2', models.CharField(max_length=255, verbose_name='Название 2')),
                ('description_2', models.CharField(max_length=255, verbose_name='Описание 2')),
                ('image', models.ImageField(upload_to='porrtfolio_image/', verbose_name='Изоброжение')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
    ]
