# Generated by Django 5.0.1 on 2024-01-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='description2',
            field=models.CharField(default=1, max_length=255, verbose_name='Заголовок2'),
            preserve_default=False,
        ),
    ]
