# Generated by Django 5.0.1 on 2024-01-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_qualification_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='procent',
            field=models.IntegerField(default=1, verbose_name='Процент'),
            preserve_default=False,
        ),
    ]
