# Generated by Django 5.0.1 on 2024-01-30 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_qualification_procent'),
    ]

    operations = [
        migrations.CreateModel(
            name='lastproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='last_project_image/', verbose_name='Изоброжение')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Последний Проект',
            },
        ),
        migrations.AlterField(
            model_name='qualification',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='description2',
            field=models.CharField(max_length=255, verbose_name='Описание2'),
        ),
    ]
