# Generated by Django 5.0.1 on 2024-01-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_lastproject_alter_qualification_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('job', models.CharField(max_length=255, verbose_name='работа')),
                ('image', models.ImageField(upload_to='review_image/', verbose_name='Изоброжение')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
