# Generated by Django 5.0.1 on 2024-01-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image_last/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Новость ',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('price', models.CharField(max_length=255, verbose_name='Цена')),
                ('plan1', models.CharField(max_length=255, verbose_name='План1')),
                ('plan2', models.CharField(max_length=255, verbose_name='План2')),
                ('plan3', models.CharField(max_length=255, verbose_name='План3')),
            ],
            options={
                'verbose_name': 'План',
                'verbose_name_plural': 'Планы',
            },
        ),
        migrations.AlterModelOptions(
            name='lastproject',
            options={'verbose_name': 'Последние Проекты', 'verbose_name_plural': 'Последние Проекты'},
        ),
        migrations.RemoveField(
            model_name='lastproject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lastproject',
            name='title',
        ),
        migrations.RemoveField(
            model_name='review',
            name='description',
        ),
        migrations.RemoveField(
            model_name='review',
            name='job',
        ),
        migrations.AddField(
            model_name='lastproject',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='review',
            field=models.TextField(default=1, verbose_name='Отзыв'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='work',
            field=models.CharField(default=1, max_length=255, verbose_name='Работа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lastproject',
            name='image',
            field=models.ImageField(upload_to='last_image/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(upload_to='image_review/', verbose_name='Фото'),
        ),
    ]
